---
title: "enrichmentHeatmap"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
```

```{r}
library(tidyverse)
library(readxl)
```


Defines functions that read each enrichment file in a specific folder, concats all files in one big table and adds one extra column that specifies the tissue name. 
```{r }

read_concat_files = function(myFolder) {
  filenames <- list.files(myFolder, pattern="*.xlsx", full.names=TRUE)
  tibs <- lapply(filenames, read_xls_files)
  for(i in 1:(length(tibs)-1)) { 
    tibs[[i+1]] = dplyr::bind_rows(tibs[[i]], tibs[[i+1]])
    }
  return(tibs[[length(tibs)]])
}

#provides functionality to read multiple tissue enrichment files
read_xls_files = function(file) {
  f <- str_split(file, "/", simplify = TRUE)
  n <- length(f)
  df <- read_excel(file, col_types= c("text","text","numeric","numeric","numeric","numeric","numeric","numeric","numeric")) %>% mutate(tissue = str_split(f[n], "_TiP", simplify = TRUE)[1])
  return(df)
}

```

Run functions to prepare data for plotting
```{r warning= FALSE}

my_folder <- "../Manuskript/Julia_Analysen/results/parameter/enrichment/all_enrich_julia/CC/"
my_heatmap_file <- "../Manuskript/Figures/expressionEnrichmentHeatmap.pdf"

dat_enr <- read_concat_files(my_folder)

```

Run a clustering to reoder tissues
```{r}
#filter for sign results
dat_enr %>% filter(`P-value-corrected`<0.05) %>% select(tissue, Association_term, `P-value-corrected`, OR) -> clustdata
clustdata %>% select(tissue, Association_term, `P-value-corrected`) -> temp
#prepare tibble for conversion into matrix
temp %>% pivot_wider(names_from=c(Association_term), values_from= c('P-value-corrected')) -> clustdata_wide
rm(temp)
clustdata_wide %>% mutate_all(~replace(.,is.na(.), 0)) -> temp
#convert to matrix
as.matrix(column_to_rownames(temp, var = "tissue")) -> matrix
rm(temp)

#cluster tissues
ord <- hclust( dist(matrix, method = "euclidean"))$order
#ord
#cluster go terms
ord_go <- hclust( dist(t(matrix), method = "euclidean"))$order
ord_go
```



Now we plot the heatmap and save it to file "my_heatmap_file" as pdf
```{r}
# defines colours used in the heatmap
cols = RColorBrewer::brewer.pal(5, "Blues")
cols = cols[2:5]

p <- clustdata %>% 
  mutate(Association_term = factor(Association_term, levels = colnames(matrix)[ord_go])) %>% 
  mutate(tissue = factor(tissue, levels = rownames(matrix)[ord])) %>%
  ggplot(aes(tissue, Association_term)) + 
  geom_tile(fill= "white") + 
  theme_light() + 
  theme(panel.spacing = unit(0.25, "lines"),axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),panel.grid.major.y = element_line(colour = "grey", linetype ="dotted")) + 
  geom_point(aes(size = OR, fill = `P-value-corrected`, colour = `P-value-corrected`), alpha = 0.7) +
  scale_color_gradientn(colors = (cols)) + 
  coord_flip() +
  labs(x = "", y = "") + 
  guides(fill = F)

# printing (cm)
A4width = 21
A4height = 29.7
  
ggsave(my_heatmap_file, plot = p, width = 0.4*A4width, height = 0.175*A4height, scale = 1.5)

p
```



